'use client';

import type { FormEvent } from "react";
import { useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase/browser";

type Resource = "categories" | "pharmacies" | "medicines" | "inventory" | "orders" | "prescriptions";
type RecordMap = Record<Resource, Array<Record<string, unknown>>>;
const emptyRecords: RecordMap = { categories: [], pharmacies: [], medicines: [], inventory: [], orders: [], prescriptions: [] };
const catalogResources: Resource[] = ["medicines", "categories", "pharmacies", "inventory"];
const supabase = createSupabaseBrowserClient();
const fields: Record<Resource, Array<[string, string, boolean]>> = {
	categories: [["name", "Category name", true], ["slug", "Slug", true]], pharmacies: [["name", "Pharmacy name", true], ["slug", "Slug", true], ["address_line1", "Address", true], ["city", "City", true], ["phone", "Phone", false]], medicines: [["name", "Medicine name", true], ["generic_name", "Generic name", false], ["brand_name", "Brand name", false], ["form", "Form", false], ["strength", "Strength", false], ["pack_size", "Pack size", false]], inventory: [["pharmacy_id", "Pharmacy ID", true], ["medicine_id", "Medicine ID", true], ["available_quantity", "Quantity", true], ["price", "Price", true], ["mrp", "MRP", false], ["delivery_fee", "Delivery fee", false]], orders: [], prescriptions: []
};

export default function AdminPage() {
	const [records, setRecords] = useState<RecordMap>(emptyRecords); const [resource, setResource] = useState<Resource>("medicines"); const [form, setForm] = useState<Record<string, string>>({}); const [message, setMessage] = useState("Sign in to continue"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [authenticated, setAuthenticated] = useState(false);
	useEffect(() => { supabase.auth.getSession().then(({ data }) => setAuthenticated(Boolean(data.session))); }, [supabase.auth]);
	async function signIn(event: FormEvent) { event.preventDefault(); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) return setMessage(error.message); setAuthenticated(true); setMessage("Signed in. Loading live records..."); void loadRecords(); }
	async function loadRecords() { const response = await fetch("/api/admin/catalog"); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to load records"); setRecords(data); setMessage("Connected to live Supabase data."); }
	async function createRecord(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/catalog", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resource, values: form }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to create record"); setForm({}); setMessage(`${resource} record created.`); void loadRecords(); }
	async function removeRecord(id: string) { if (!window.confirm("Delete this record?")) return; const response = await fetch("/api/admin/catalog", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resource, id }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to delete record"); setMessage("Record deleted."); void loadRecords(); }
	async function signOut() { await supabase.auth.signOut(); setAuthenticated(false); setRecords(emptyRecords); setMessage("Signed out"); }
	if (!authenticated) return <main className="admin-login"><form onSubmit={signIn}><strong>MEDI<span>NOW</span></strong><small>ADMIN OPERATIONS</small><h1>Sign in</h1><p>Use an authenticated Supabase account with admin role.</p><label>Email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type="password" required value={password} onChange={(event) => setPassword(event.target.value)} /></label><button type="submit">SIGN IN</button><a href="/medinow1">BACK TO CUSTOMER APP</a><em>{message}</em></form></main>;
	return <main className="admin-screen"><aside className="admin-sidebar"><strong>MEDI<span>NOW</span></strong><small>OPERATIONS CONSOLE</small><nav><button className={resource === "orders" ? "active" : ""} type="button" onClick={() => setResource("orders")}>ORDERS</button><button className={resource === "prescriptions" ? "active" : ""} type="button" onClick={() => setResource("prescriptions")}>PRESCRIPTIONS</button>{catalogResources.map((item) => <button className={resource === item ? "active" : ""} key={item} type="button" onClick={() => { setResource(item); setForm({}); }}>{item.toUpperCase()}</button>)}</nav><button className="admin-signout" type="button" onClick={() => void signOut()}>SIGN OUT</button></aside><section className="admin-main"><header className="admin-header"><div><small>ADMINISTRATION</small><h1>MEDINOW operations</h1><p>Live catalog, fulfillment, and prescription workspace.</p></div><a href="/medinow1">OPEN CUSTOMER APP</a></header><div className="admin-stat-grid">{catalogResources.concat(["orders", "prescriptions"]).map((item) => <button type="button" key={item} onClick={() => setResource(item)}><strong>{records[item].length}</strong><span>{item.toUpperCase()}</span></button>)}</div><p className="admin-status">{message}</p><div className="admin-grid">{catalogResources.includes(resource) && <section className="admin-panel"><h2>Add {resource.slice(0, -1)}</h2><p>Creates a real database record. No sample data is inserted.</p><form onSubmit={createRecord}>{fields[resource].map(([name, label, required]) => <label key={name}>{label}<input required={required} value={form[name] ?? ""} onChange={(event) => setForm({ ...form, [name]: event.target.value })} placeholder={label} /></label>)}<button type="submit">CREATE RECORD</button></form></section>}<section className="admin-panel admin-panel--wide"><div className="admin-panel-heading"><div><h2>{resource.toUpperCase()}</h2><p>{records[resource].length} live records loaded</p></div><button type="button" onClick={() => void loadRecords()}>REFRESH</button></div><div className="admin-records">{records[resource].length === 0 ? <div className="admin-empty">No records yet.</div> : records[resource].map((record) => <article key={String(record.id)}><div><strong>{String(record.name ?? record.medicine_name ?? record.status ?? record.id)}</strong><small>{String(record.slug ?? record.prescription_status ?? record.price ?? record.created_at ?? "")}</small></div>{catalogResources.includes(resource) && <button type="button" onClick={() => void removeRecord(String(record.id))}>DELETE</button>}</article>)}</div></section></div></section></main>;
}